packages:
  - apps/*
  - packages/**/*
catalog:
  react: ">=19"
  react-dom: ">=19"
  next: ">=15"
  motion: ">=12"
  "react-hook-form": ">=7"
  "@tanstack/react-table": ">=8"
onlyBuiltDependencies:
  - "@swc/core"
  - esbuild
  - sharp
